Online_Shop/urls.py
from . import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  include , url

urlpatterns = [
    path('', views.home_page , name='home_page'),
    path('our-story/' , views.our_story , name='our_story'),
    path('contact/' , views.contact , name='contact'),
    path('send_email/' , views.send_email , name='send_email'),
    path('help/' , views.help , name= 'help'),
    path('admin/', admin.site.urls),

    path('order/', include('order.urls')),
    path('customer/', include('customer.urls')),
    path('product/', include('product.urls')),
    path('product/', views.product_redirect , name='product_redirect'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    #customer/sign-up/
    path('sign-up/' , views.SignUp, name='SignUp'),
    #customer/info/
    path('info/' , views.info, name='info'),
    #customer/login/
    path('login/' , views.request_login, name='request_login'),
    #customer/logout/
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'


urlpatterns = [
    # path('' , views.index , name='index'),
    # path('<category_slug>/<item_slug>/<quantity>/', views.add_to_cart, name='add_to_cart'),
    # path('cart/', views.cart_detail, name='cart_detail'),
    # path('add/<item_slug>/', views.add_to_cart, name='add_to_cart'),
	# path('remove/<item_slug>/', views.remove_from_cart, name='remove_from_cart'),
	# path('ajax/quick_add/', views.quick_add, name='quick_add'),
	# path('ajax/increment/', views.increment, name='increment'),
    # path('ajax/decrement/', views.decrement, name='decrement'),
	# path('customer-info/', views.customer_info , name='customer_info'),
	path('checkout/', views.checkout, name='checkout'),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from order.models import Orders
# Create your models here.


class Customers(AbstractUser):
    address_line1 = models.CharField(max_length=100)
    address_line2 = models.CharField(max_length=100)
    country = models.CharField(max_length=128 , null=True, blank=True)
    city = models.CharField(max_length=128, null=True, blank=True)
    zip_code = models.CharField(max_length=128, null=True, blank=True)

customer/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import logout , login
from django.urls import reverse_lazy
from django.views import generic, View
# Create your views here.
from django.views.generic import CreateView
from django.contrib.auth.models import auth
from .models import Customers
from django.contrib.auth.decorators import login_required
from order.models import Orders


def SignUp(request):
     if request.method == 'POST':
            first_name = request.POST.get('FName')
            last_name = request.POST.get('LName')
            email = request.POST.get('inputEmail')
            password = request.POST.get('password')
            confirmPassword = request.POST.get('confirmPassword')

            if Customers.objects.filter(username=email).exists():
                print("Already Exist")
                context = { 'message' : "Account already Exist with this E-mail."}
                return render(request , 'customer/signUp.html' , context)
            else:
                if password == confirmPassword:
                    user = Customers.objects.create_user(first_name=first_name,
                                                         username=email,
                                                         last_name=last_name,
                                                         email=email,
                                                         password=password)
                    user.save()
                    print("Successful")
                    return render(request , 'customer/customer_info.html')
                    # try:
                    #     user = Customers.objects.create_user(first_name=first_name,
                    #                                          username=email,
                    #                                          last_name=last_name,
                    #                                          email=email,
                    #                                          password=password)
                    #     user.save()
                    #     print("Successful")
                    #     return render(request , 'customer/customer_info.html')
                    # except:
                    #     print("Something went wrong while creating account")
                    #     context = { 'message' : "Something went wrong while creating account."}
                    #     return render(request , 'customer/signUp.html' , context)
     else:
         print("Accessing First Time")
         return render(request , 'customer/signUp.html')


#this is a logout view

class LogoutView(View):
    def get(self, request,  *args, **kwargs):
        del request.session['is_login']
        logout(request)
        return redirect('/')

#handles the request for Logging in of Customer
def request_login(request):
    if request.method == 'POST':
        email = request.POST.get('id_username')
        password = request.POST.get('id_password')
        user = auth.authenticate(request, username = email, password= password)
        if user is not None:
            auth.login(request, user)
            request.session['is_login'] = 'true'
            return render(request , 'customer/customer_info.html')
        else:
            return render(request , 'customer/login_error.html')
            # return render(request, '401.html')
    else:
        login = request.session.get('is_login' , 'false')
        if  login == 'true':
            return render(request , 'customer/customer_info.html')
        return render(request , 'customer/login.html')


@login_required()
def info(request):
    return render(request , 'customer/customer_info.html')
    # try:
    #     login = request.session['is_login']
    #     if  login == True:
    #         UserEmail = request.session['email']
    #         try:
    #             UserID = Customers.objects.get(email=UserEmail)
    #         except:
    #             return render(request , 'error.html')
    #         else:
    #             OrderIDs = Orders.objects.filter(customer_id=UserID)
    #             context = { 'UserEmail' : UserEmail , 'OrderIDs' : OrderIDs }
    #             return render(request , 'customer/customer_info.html', context)
    # except KeyError:
    #     return render(request , 'customer/login_error.html')

customer/templates/customer/customer_info.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<title>Account-Online Shop</title>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vl {
    border-left: 1px solid grey;
    height: 220px;
}

</style>
</head>
<body>

<div class="container main content">
    <div class="w3-container">
        <br><br>
        <h1 style="font-weight: 900"> Account Details </h1>
        <br>
    </div>

    <div class="w3-row">
        <div class="w3-col w3-container m8 l3 w3-white">
            <p>
            <h2 class="name"><a href="#" style="font-size: 23px; font-weight: 1100;" title="My Account">Usama Maqsood</a></h2>
                <p class="w3-large">umalick22@gmail.com</p>
                     <h3 style="font-weight: 900">Primary Address</h3>
                         <div class="address note">
                             <p class="w3-large">No address</p>
                            <p>
                             <a href="#" class="w3-large" >View Address (0)</a>
                             </p>
                        </div>
            </p>
        </div>
        <div class="w3-col w3-container m8 l8">
            <div class="vl">
                <div class="w3-container">
                    <h3 style="font-weight: 900" >Order History</h3>
                    <p class="w3-large">You haven’t placed any orders yet.</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="w3-row">
    <div class="w3-threequarter w3-container">
        <h1></h1>
    </div>
    <div class="w3-quarter w3-container">
        <h2><a href="{% url 'customer:logout' %}" style="font-size: 23px; font-weight: 1100;" title="Logout">LOGOUT</a></h2>
    </div>
</div>
<br><br>

</body>
</html>

{% endblock content %}

customer/templates/customer/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>LOGIN</title>
    <br><br><br><br>
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <h1>Customer LogIn</h1> <br><br>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Email</label></td>
                        <td><input id="id_username" name="id_username"
                                   type="text" class="form-control" placeholder="Email"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="id_password"
                                   type="password" class="form-control" placeholder="Password"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login"
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
                <br><br><br><br>
            </form>
        </div>
    </div>
{% endblock content %}

customer/templates/customer/login_error.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<title>Error</title>

	<!-- content page -->
	<section class="bgwhite p-t-66 p-b-38">
		<div class="container">
			<div class="row">
                <div class="col-md-8 p-b-30">
					<h3 class="m-text26 p-t-15 p-b-16">
						Something Went Wrong. <br>
                        Please

                        and try again.
					</h3>
				</div>
			</div>
		</div>
	</section>

{% endblock content %}

customer/templates/customer/signUp.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<title>SIGN UP</title>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vl {
    border-left: 1px solid grey;
    height: 220px;
}

</style>
</head>

<section class="bgwhite p-t-66 p-b-60">
    <div class="container">
        <div class="row">
            <div class="col-md-3 p-b-30"></div>
            <div class="col-md-6 p-b-30">
                <form method="post" >
                    {% csrf_token %}

                    <h4 class="m-text26 p-b-36 p-t-15">
                        Sign Up
                    </h4>
                    <div class="bo4 of-hidden size15 m-b-20">
                        <input type="text" class="sizefull s-text7 p-l-12 p-r-22" name="FName" id="FName" placeholder="First Name" required>
                    </div>
                    <div class="bo4 of-hidden size15 m-b-20">
                        <input type="text" class="sizefull s-text7 p-l-22 p-r-22"  name="LName" id="LName" placeholder="Last Name" required>
                    </div>
                    <div class="bo4 of-hidden size15 m-b-20">
                        <input type="email" class="sizefull s-text7 p-l-22 p-r-22"  name="inputEmail" id="inputEmail" placeholder="Email@Online_Shop.com" required>
                    </div>
                    <div class="bo4 of-hidden size15 m-b-20">
                        <input type="password" class="sizefull s-text7 p-l-22 p-r-22" name="password" id="password" placeholder="Password" required>
                    </div>
                    <div class="bo4 of-hidden size15 m-b-20">
                        <input type="password" class="sizefull s-text7 p-l-22 p-r-22"  name="confirmPassword" id="confirmPassword" placeholder="Confirm Password" required>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Sign Up" onclick="return Validate()"/>

                </form>
            </div>
        </div>

        <div class="w3-row">
            <div class="w3-threequarter w3-container">
                <h5></h5>
            </div>
            <div class="w3-quarter w3-container">
                <div class="form row">
                    <h5 class="m-text16 p-b-26 p-t-11" style="font-size: 16px;">Already have an account?
                        <a href="#" class="m-text16 p-b-26 p-t-11" style="font-size: 16px;" title="Logout">LOGIN</a></h5>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    function Validate() {
        var password = document.getElementById("password").value;
        var confirmPassword = document.getElementById("confirmPassword").value;
        if (password != confirmPassword) {
            alert("Passwords do not match.");
            return false;
        }
        return true;
    }
</script>


{% endblock content %}