Online_Shop/urls.py
from . import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  include , url

urlpatterns = [
    path('', views.home_page , name='home_page'),
    path('our-story/' , views.our_story , name='our_story'),
    path('contact/' , views.contact , name='contact'),
    path('send_email/' , views.send_email , name='send_email'),
    path('help/' , views.help , name= 'help'),
    path('admin/', admin.site.urls),

    path('order/', include('order.urls')),
    path('customer/', include('customer.urls')),
    path('product/', include('product.urls')),
    path('product/', views.product_redirect , name='product_redirect'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'


urlpatterns = [
    # path('' , views.index , name='index'),
    # path('<category_slug>/<item_slug>/<quantity>/', views.add_to_cart, name='add_to_cart'),
    # path('cart/', views.cart_detail, name='cart_detail'),
    # path('add/<item_slug>/', views.add_to_cart, name='add_to_cart'),
	# path('remove/<item_slug>/', views.remove_from_cart, name='remove_from_cart'),
	# path('ajax/quick_add/', views.quick_add, name='quick_add'),
	# path('ajax/increment/', views.increment, name='increment'),
    # path('ajax/decrement/', views.decrement, name='decrement'),
	# path('customer-info/', views.customer_info , name='customer_info'),
	path('checkout/', views.checkout, name='checkout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # /product/
    path('' , views.shop, name='temp'),
    # /products/id/
    # path('<category_slug>/', views.category_list, name='category_list'),
    #/products/id/product_name

    #/product/slug/
    path('<product_slug>/' , views.product_info , name='product_info'),



    # path('<article_slug>/', views.product_info, name='product_info'),
    #path('<int:article>/', views.product_info, name='product_info'),
]

product/models.py
from django.db import models
from datetime import datetime, timedelta
from django.core.validators import MaxValueValidator , MinValueValidator
#from django.core.urlresolvers import reverse

def self(args):
    pass

class category(models.Model):
    name = models.CharField(max_length=250 , unique=True)
    slug = models.SlugField(max_length=200 , db_index=True , unique=True)
    created_at = models.DateTimeField(default= datetime.now())

    class Meta:
        ordering = ('name' , )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Products(models.Model):
    product_id = models.ForeignKey(category, on_delete=models.DO_NOTHING , default='NULL')
    title = models.CharField(max_length = 250)
    code = models.CharField(max_length=20 , default='NULL')
    slug = models.SlugField(max_length=200 , db_index=True , unique=True)
    product_type = models.CharField(max_length = 50)
    long_description = models.CharField(max_length = 500)
    short_description = models.CharField(max_length = 300)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default = 0)
    ranking = models.PositiveIntegerField(default=1 , validators=[MaxValueValidator(10) , MinValueValidator(1)])
    created_at = models.DateTimeField(default= datetime.now())
    updated_at = models.DateTimeField(default= datetime.now())
    front_image = models.ImageField(upload_to='Online_Shop/')

    class Meta:
        ordering = ('-created_at' , )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        index_together = (('id' , 'slug') , )
    def __str__(self):
        return self.title

class product_images(models.Model):
    product_id = models.ForeignKey(Products, on_delete=models.DO_NOTHING)
    display_image = models.ImageField(upload_to='Online_Shop/')

   # def __str__(self):
       # return self. product_id

class Locations(models.Model):
    location_name=models.CharField(max_length=100)

    def __str__(self):
        return self.location_name

class Pricing(models.Model):
    product_id = models.ForeignKey(Products , on_delete=models.CASCADE)
    location = models.ForeignKey(Locations , on_delete=models.CASCADE)
    price = models.FloatField(default=models.NOT_PROVIDED)
    class Meta:
        unique_together = ('product_id', 'location')




class Sale(models.Model):
    product = models.ForeignKey(Products, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.product

class Sale_Details(models.Model):
    sale_id = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    sale_name = models.CharField(max_length=20, default='NULL', editable=True)
    sale_percentage = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()
    locations = models.ForeignKey(Locations, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = ('sale_id', 'product_id')

#
	#def__str__(self):
	# 	return self.Songtitle

product/views.py
import datetime
from urllib import request

from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
# Create your views here.
from product.models import Products

def temp(request):
    return render(request , 'product/product.html')

def shop(request):
    all_products = Products.objects.filter(available=True).order_by('-ranking' , '-created_at')

    if  all_products:

        print("Displaying Products!")
        num_products = all_products.count()
        if num_products > 12:
            pages = num_products/12
            orphans = num_products % pages
        else:
            pages = 1
            orphans = 0

        paginator = Paginator(all_products, 12 , orphans) # Show 12 products per page
        page = request.GET.get('page')
        products = paginator.get_page(page)
        ttl_page = int(pages)
        list = []
        for i in range(1, ttl_page+1):
            list.append(i)

        now = datetime.date.today()
        few_weeks = now - datetime.timedelta(days=14)

        context = { 'products' : products , 'list' : list , 'few_weeks' : few_weeks}
        return render(request , 'product/product.html', context)
    else:
        return render(request , 'product/product.html')


def product_info(request, product_slug):

    #return HttpResponse("<h2> say hello! : "+ str(article_id) +" and category is :" + str(category_id) +  "</h2>")
    try:

        product_info = Products.objects.get(slug = product_slug)

        print("===================================")
        print("===================================")
        print("===================================")

        all_products = Products.objects.filter(available=True).order_by('-ranking' , '-created_at')

        context = { 'product_info' : product_info , 'related_products' : all_products}
        

        return render(request , 'product/product-info.html' , context)


        # now = datetime.date.today()
        # few_weeks = now - datetime.timedelta(days=14)
        # P_ranking = product_info.ranking
        # P_type = product_info.product_type
        # try:
        #     products_by_type = Products.objects.filter(available=True , product_type=P_type).\
        #         exclude(title=product_info.title).order_by('-ranking' , '-created_at')
        #     products_by_rank =  Products.objects.filter(available=True , ranking=P_ranking).\
        #         exclude(title=product_info.title).order_by('-ranking' , '-created_at')
        #     related_products = (products_by_type | products_by_rank).distinct()
        #     context = { 'product_info' : product_info  , 'few_weeks' : few_weeks , 'related_products' : related_products}
        #     return render(request , 'product/product-detail.html' , context)
        # except:
        #     context = {'product_info' : product_info }
        #     return render(request , 'product/product-detail.html' , context)
    except:
        return render(request , 'error.html')

product/templates/product/index.html
<title>Online_Shop</title>
<center>
{% if all_categories %}
    <ul>
       <h1> Please Select Category </h1>
        {% for categories in all_categories %}
            <a href="{% url 'products:category_list' categories.slug %}"> {{categories.name}} </a> <br/>
        {% endfor %}
    </ul>
{% else %}
    <h3>Nothing found!</h3>
{% endif %}

    <p>You have visited this page {{ request.session.num_visits }}{% if request.session.num_visits == 1 %} time{% else %} times{% endif %}.</p>
    <h1>{{request.session.name}}</h1>
    <h1>{{request.session.ip}}</h1>
</center>
x

product/templates/product/product-detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<title>Product Detail</title>

	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="{% url 'home_page' %}" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'products:shop'  %}" class="s-text16">
			Products
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
            {{ product_info.title }}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

                     <div class="slick3">
						    <div class="item-slick3" data-thumb="{{ product_info.front_image.url }}">
							    <div class="wrap-pic-w">
								    <img src="{{ product_info.front_image.url }}" alt="IMG-PRODUCT">
							    </div>
						    </div>

                        {% for product_image in product_info.product_images_set.all %}
                            <div class="item-slick3" data-thumb="{{ product_image.display_image.url }}">
                                 <div class="wrap-pic-w">
                                     <img src="{{ product_image.display_image.url }}" alt="IMG-PRODUCT">
                                 </div>
                            </div>
                         {% endfor %}
                     </div>
                </div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{ product_info.title }}
				</h4>

				<span class="m-text17">
					$22
				</span>

				<p class="s-text8 p-t-10 ">
                    <span style="font-size: 16px;">{{ product_info.short_description }}</span>
				</p>

				<!-- Write Code to add products in CART -->
				<div class="p-t-33 p-b-60">
					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>

							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10">
								<!-- Button -->
								<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
									Add to Cart
								</button>
							</div>
						</div>
					</div>
				</div>

				<div class="p-b-45">
					<span class="s-text8 m-r-35">SKU: MUG-01</span>
					<span class="s-text11" style="font-size: 16px;" >{{product_info.product_type}}</span>
				</div>

				<!--  -->
				<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Description
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							 <span style="font-size: 15px;">{{ product_info.long_description }}</span>
						</p>
					</div>
				</div>

				<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Additional information
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							Additional information. :)
						</p>
					</div>
				</div>
            </div>
        </div>
    </div>



	<!-- Other Products -->
    <div>
	<section class="relateproduct bgwhite p-t-45 p-b-138">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Related Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

                    {% for products in related_products%}
                        <div class="item-slick2 p-l-15 p-r-15">
						<!-- Block2 -->
						<div class="block2">

                            <!--Use this div in else condition when done with sale-->
							<!--<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelsale">-->
                            {% if products.created_at|date:"Y-m-d" > few_weeks|date:"Y-m-d" %}
                            <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
                                {% else %}
                            <div class="block2-img wrap-pic-w of-hidden pos-relative">
                                {% endif %}

								<img src="{{ products.front_image.url }}" alt="IMG-PRODUCT">

								<div class="block2-overlay trans-0-4">

                                    <div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Add to Cart
										</button>
									</div>
								</div>
							</div>

                            <center>
							<div class="block2-txt p-t-20">
								<a href="{% url 'products:product_info' products.code %}" class="block2-name dis-block s-text3 p-b-5">
                                   {{ products.title}}
                                </a>
                                <span class="block2-price m-text6 p-r-5"> $75.00 </span>
                            </div>
                            </center>

                        </div>
					</div>

                    {%endfor%}

                </div>
			</div>
            </div>
        </div>
	</section>

    </div>


{% endblock content %}

product/templates/product/product-info.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<title>Product Detail</title>

    <!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="{% url 'home_page' %}" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="#" class="s-text16">
			Products
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
            {{ product_info.title }}
		</span>
	</div>

    <!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

                     <div class="slick3">
						    <div class="item-slick3" data-thumb="{{ product_info.front_image.url }}">
							    <div class="wrap-pic-w">
								    <img src="{{ product_info.front_image.url }}" alt="IMG-PRODUCT">
							    </div>
						    </div>

                        {% for product_image in product_info.product_images_set.all %}
                            <div class="item-slick3" data-thumb="{{ product_image.display_image.url }}">
                                 <div class="wrap-pic-w">
                                     <img src="{{ product_image.display_image.url }}" alt="IMG-PRODUCT">
                                 </div>
                            </div>
                         {% endfor %}
                     </div>
                </div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{ product_info.title }}
				</h4>

				<span class="m-text17">
					$22
				</span>

				<p class="s-text8 p-t-10 ">
                    <span style="font-size: 16px;">{{ product_info.short_description }}</span>
				</p>

				<!-- Write Code to add products in CART -->
				<div class="p-t-33 p-b-60">
					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>

							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10">
								<!-- Button -->
								<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
									Add to Cart
								</button>
							</div>
						</div>
					</div>
				</div>

				<div class="p-b-45">
					<span class="s-text8 m-r-35">SKU: MUG-01</span>
					<span class="s-text11" style="font-size: 16px;" >{{product_info.product_type}}</span>
				</div>

				<!--  -->
				<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Description
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							 <span style="font-size: 15px;">{{ product_info.long_description }}</span>
						</p>
					</div>
				</div>

				<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Additional information
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							Additional information. :)
						</p>
					</div>
				</div>
            </div>
        </div>
    </div>


    <div>
        <section class="relateproduct bgwhite p-t-45 p-b-138">
            <div class="container">
                <div class="sec-title p-b-60">
                    <h3 class="m-text5 t-center">
                        Related Products
                    </h3>
                </div>

                <!-- Slide -->
                <div class="wrap-slick2">
                    <div class="slick2">
                        <!-- Product -->
                        {% if related_products %}
                        {% for products in related_products%}
                        <div class="item-slick2 p-l-15 p-r-15">
                            <!-- Block2 -->
                            <div class="block2">

                                <div class="block2-img wrap-pic-w of-hidden pos-relative">
                                    <img src="{{ products.front_image.url }}" alt="IMG-PRODUCT">

                                    <div class="block2-overlay trans-0-4">

                                        <div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
                                            <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                                Add to Cart
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                <center>
                                    <div class="block2-txt p-t-20">
                                        <a  href="{% url 'product:product_info' product_slug=products.slug %}" class="block2-name dis-block s-text3 p-b-5">
                                            {{ products.title}}
                                        </a>
                                        <span class="block2-price m-text6 p-r-5"> $75.00 </span>
                                    </div>
                                </center>

                            </div>
                        </div>

                        {% endfor %}
                        {% endif %}

                    </div>
                </div>

            </div>
        </section>
    </div>





{% endblock content %}

product/templates/product/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<title>Products</title>

    <!-- Title Page -->
<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/static/Online_Shop/images/heading-pages-02.jpg);">
    <h2 class="l-text2 t-center">
        <!--Women-->
        Our Products
    </h2>
    <p class="m-text13 t-center">
        <!--New Arrivals Women Collection 2018-->
        New Arrivals 2020
    </p>
</section>

    <!-- Content page -->
<section class="bgwhite p-t-55 p-b-65">
    <div class="container">

        <div class="row">
            <!-- Product -->
            {% if products %}
                {% for product in products %}
                    <div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
                        <!-- Block2 -->
                        <div class="block2">
                            {% if products.created_at|date:"Y-m-d" > few_weeks|date:"Y-m-d" %}
                            <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
                                {% else %}
                                <div class="block2-img wrap-pic-w of-hidden pos-relative">
                                    {% endif %}
                                <img  src="{{ product.front_image.url }}" alt="IMG-PRODUCT">
                                <div class="block2-overlay trans-0-4">
                                    <div class="block2-btn-addcart w-size1 trans-0-4">
                                        <!-- Button -->
                                        <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                            Add to Cart
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <center>
                            <div class="block2-txt p-t-20">
                                <a href="{% url 'product:product_info' product_slug=product.slug %}" class="block2-name dis-block s-text3 p-b-5">
                                    {{product.title}}
                                </a>
                                <span class="block2-price m-text6 p-r-5">
                                    $75.00
                                </span>
                            </div>
                            </center>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                   <h3>Shop is empty!</h3>
            {% endif %}
        </div>

        <!-- Pagination -->
        <div class="pagination flex-m flex-w p-t-26">
             {% for i in list %}
                {% if i == products.number %}
                    <a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">{{i}}</a>
                {% else %}
                    <a href="?page={{ i }}" class="item-pagination flex-c-m trans-0-4">{{i}}</a>
                {% endif %}
             {% endfor %}
        </div>

    </div>
    </div>
</section>

{% endblock content %}